// <auto-generated />
using System;
using IT3045_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045Final.Migrations
{
    [DbContext(typeof(SportsContext))]
    [Migration("20231206042151_InitialSports")]
    partial class InitialSports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045_Final.Models.Sports", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Birthdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfMatchesPlayed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SportsTeamMember");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = "12/1/2004",
                            NoOfMatchesPlayed = "12",
                            SportsName = "Cricket",
                            TeamMemberName = "James Smith"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = "2/10/2007",
                            NoOfMatchesPlayed = "12",
                            SportsName = "Soccer",
                            TeamMemberName = "Robert Johnson"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = "9/4/2008",
                            NoOfMatchesPlayed = "12",
                            SportsName = "BasketBall",
                            TeamMemberName = "Maria Garcia"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = "11/9/2005",
                            NoOfMatchesPlayed = "12",
                            SportsName = "Hockey",
                            TeamMemberName = "Taylor Miller"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = "6/12/2008",
                            NoOfMatchesPlayed = "12",
                            SportsName = "Soccer",
                            TeamMemberName = "Davis Jones"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
