// <auto-generated />
using System;
using IT3045_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045Final.Migrations
{
    [DbContext(typeof(BaseballTeamContext))]
    partial class BaseballTeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045_Final.Models.BaseballTeam", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Founded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorldSeriesChampionships")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseballTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Phoenix",
                            Founded = "1998",
                            State = "Arizona",
                            TeamName = "Diamondbacks",
                            WorldSeriesChampionships = "1"
                        },
                        new
                        {
                            Id = 2,
                            City = "Atlanta",
                            Founded = "1871",
                            State = "Georgia",
                            TeamName = "Braves",
                            WorldSeriesChampionships = "4"
                        },
                        new
                        {
                            Id = 3,
                            City = "Baltimore",
                            Founded = "1894",
                            State = "Maryland",
                            TeamName = "Orioles",
                            WorldSeriesChampionships = "3"
                        },
                        new
                        {
                            Id = 4,
                            City = "Boston",
                            Founded = "1901",
                            State = "Massachusetts",
                            TeamName = "Red Sox",
                            WorldSeriesChampionships = "9"
                        },
                        new
                        {
                            Id = 5,
                            City = "Chicago",
                            Founded = "1876",
                            State = "Illinois",
                            TeamName = "Cubs",
                            WorldSeriesChampionships = "3"
                        },
                        new
                        {
                            Id = 6,
                            City = "Chicago",
                            Founded = "1901",
                            State = "Illinois",
                            TeamName = "White Sox",
                            WorldSeriesChampionships = "3"
                        },
                        new
                        {
                            Id = 7,
                            City = "Cincinnati",
                            Founded = "1881",
                            State = "Ohio",
                            TeamName = "Reds",
                            WorldSeriesChampionships = "5"
                        },
                        new
                        {
                            Id = 8,
                            City = "Cleveland",
                            Founded = "1894",
                            State = "Ohio",
                            TeamName = "Guardians",
                            WorldSeriesChampionships = "2"
                        },
                        new
                        {
                            Id = 9,
                            City = "Denver",
                            Founded = "1991",
                            State = "Colorado",
                            TeamName = "Rockies",
                            WorldSeriesChampionships = "0"
                        },
                        new
                        {
                            Id = 10,
                            City = "Detroit",
                            Founded = "1894",
                            State = "Michigan",
                            TeamName = "Tigers",
                            WorldSeriesChampionships = "4"
                        },
                        new
                        {
                            Id = 11,
                            City = "Houston",
                            Founded = "1962",
                            State = "Texas",
                            TeamName = "Astros",
                            WorldSeriesChampionships = "2"
                        },
                        new
                        {
                            Id = 12,
                            City = "Kansas City",
                            Founded = "1969",
                            State = "Missouri",
                            TeamName = "Royals",
                            WorldSeriesChampionships = "2"
                        },
                        new
                        {
                            Id = 13,
                            City = "Anaheim",
                            Founded = "1961",
                            State = "California",
                            TeamName = "Angels",
                            WorldSeriesChampionships = "1"
                        },
                        new
                        {
                            Id = 14,
                            City = "Los Angeles",
                            Founded = "1883",
                            State = "California",
                            TeamName = "Dodgers",
                            WorldSeriesChampionships = "7"
                        },
                        new
                        {
                            Id = 15,
                            City = "Miami",
                            Founded = "1991",
                            State = "Florida",
                            TeamName = "Marlins",
                            WorldSeriesChampionships = "2"
                        },
                        new
                        {
                            Id = 16,
                            City = "Milwaukee",
                            Founded = "1969",
                            State = "Wisconsin",
                            TeamName = "Brewers",
                            WorldSeriesChampionships = "0"
                        },
                        new
                        {
                            Id = 17,
                            City = "Minneapolis",
                            Founded = "1901",
                            State = "Minnesota",
                            TeamName = "Twins",
                            WorldSeriesChampionships = "3"
                        },
                        new
                        {
                            Id = 18,
                            City = "Flushing",
                            Founded = "1962",
                            State = "New York",
                            TeamName = "Mets",
                            WorldSeriesChampionships = "2"
                        },
                        new
                        {
                            Id = 19,
                            City = "Bronx",
                            Founded = "1903",
                            State = "New York",
                            TeamName = "Yankees",
                            WorldSeriesChampionships = "27"
                        },
                        new
                        {
                            Id = 20,
                            City = "Oakland",
                            Founded = "1901",
                            State = "California",
                            TeamName = "Athletics",
                            WorldSeriesChampionships = "9"
                        },
                        new
                        {
                            Id = 21,
                            City = "Philadelphia",
                            Founded = "1883",
                            State = "Pennsylvania",
                            TeamName = "Phillies",
                            WorldSeriesChampionships = "2"
                        },
                        new
                        {
                            Id = 22,
                            City = "Pittsburgh",
                            Founded = "1882",
                            State = "Pennsylvania",
                            TeamName = "Pirates",
                            WorldSeriesChampionships = "5"
                        },
                        new
                        {
                            Id = 23,
                            City = "San Diego",
                            Founded = "1969",
                            State = "California",
                            TeamName = "Padres",
                            WorldSeriesChampionships = "0"
                        },
                        new
                        {
                            Id = 24,
                            City = "San Francisco",
                            Founded = "1883",
                            State = "California",
                            TeamName = "Giants",
                            WorldSeriesChampionships = "8"
                        },
                        new
                        {
                            Id = 25,
                            City = "Seattle",
                            Founded = "1977",
                            State = "Washington",
                            TeamName = "Mariners",
                            WorldSeriesChampionships = "0"
                        },
                        new
                        {
                            Id = 26,
                            City = "St. Louis",
                            Founded = "1882",
                            State = "Missouri",
                            TeamName = "Cardinals",
                            WorldSeriesChampionships = "11"
                        },
                        new
                        {
                            Id = 27,
                            City = "Tampa Bay",
                            Founded = "1998",
                            State = "Florida",
                            TeamName = "Rays",
                            WorldSeriesChampionships = "0"
                        },
                        new
                        {
                            Id = 28,
                            City = "Arlington",
                            Founded = "1961",
                            State = "Texas",
                            TeamName = "Rangers",
                            WorldSeriesChampionships = "1"
                        },
                        new
                        {
                            Id = 29,
                            City = "Toronto",
                            Founded = "1976",
                            State = "Ontario",
                            TeamName = "Blue Jays",
                            WorldSeriesChampionships = "2"
                        },
                        new
                        {
                            Id = 30,
                            City = "Washington",
                            Founded = "1859",
                            State = "DC",
                            TeamName = "Nationals",
                            WorldSeriesChampionships = "1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
