// <auto-generated />
using IT3045_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045Final.Migrations
{
  [DbContext(typeof(SportsContext))]
  partial class SportsContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "7.0.0")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("IT3045_Final.Models.Sports", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Birthdate")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("TeamMemberName")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("SportsName")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("NoOfMatchesPlayed")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("Sports");

            b.HasData(
                  new
                  { Id = 1, TeamMemberName = "James Smith", SportsName = "Cricket", Birthdate = "12/1/2004", NoOfMatchesPlayed = "12" },
                  new
                  {Id = 2, TeamMemberName = "Robert Johnson", SportsName = "Soccer", Birthdate = "2/10/2007", NoOfMatchesPlayed = "12"},
                  new
                  {Id = 3, TeamMemberName = "Maria Garcia", SportsName = "BasketBall", Birthdate = "9/4/2008", NoOfMatchesPlayed = "12"},
                      new
                  {Id = 4, TeamMemberName = "Taylor Miller", SportsName = "Hockey", Birthdate = "11/9/2005", NoOfMatchesPlayed = "12"},
                  new
                  {Id = 5, TeamMemberName = "Davis Jones", SportsName = "Soccer", Birthdate = "6/12/2008", NoOfMatchesPlayed = "12"});
          });
#pragma warning restore 612, 618
    }
  }
}