// <auto-generated />
using IT3045_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045Final.Migrations
{
    [DbContext(typeof(TeamMemberContext))]
    partial class TeamMemberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045_Final.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Birthdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = "4/10/2004",
                            FullName = "Erin McManus",
                            Program = "Mechanical Engineering",
                            Year = "2nd"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = " ",
                            FullName = "Nivedha Balasubramanian",
                            Program = " ",
                            Year = " "
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = "6/30/1994",
                            FullName = "Josh Moore",
                            Program = "IT Software Development",
                            Year = "N/A"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = "6/5/2003",
                            FullName = "Noah Wardega",
                            Program = "Certificate in IT",
                            Year = "3rd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
